#euler 45
"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from root import has_int_root

count = 0
n = 286

while count < 1:
    Tn = n * (n + 1) // 2
    #check if pentagonal
    if has_int_root(Tn, [6, 24]):
        #check if hexagonal
        if has_int_root(Tn, [4, 8]):
            print(Tn)
            count += 1
    n += 1


